name: PR Build

on: [ pull_request ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build
      run: ./gradlew build
    - name: Docker build
        run: |
          echo $GITHUB_TOKEN | docker login https://docker.pkg.github.com -u USERNAME --password-stdin
          docker build . -t front50 -f Dockerfile.slim
          docker tag front50 docker.pkg.github.com/KeisukeYamashita/front50
          docker push docker.pkg.github.com/KeisukeYamashita/front50
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
